apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-pod-discovery
  namespace: online-boutique
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-pod-discovery
  namespace: online-boutique
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-pod-discovery
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: monitoring