apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-checkoutservice
  namespace: chaos-testing
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: checkoutservice
  delay:
    latency: "200ms"
    correlation: "100"
    jitter: "10ms"
  duration: "180s"
